### PR TITLE
Update highcharts-chart.component.ts

### PR DESCRIPTION
**Pull request by fclmman**
Added _zone.runOutsideAngular for highcharts stuff, as it hardly affects application performance due to multiple eventListeners inside highcharts itself

### CODE REVIEW

**Comment by KacperMadej** [comment]
Hi @fclmman 

Before we could accept the PR we'll need more info about the issue it's related to and what exactly is the "stuff" you mentioned.

**Comment by fclmman** [comment]
Hi, @KacperMadej, thank for such quick response. What i mentioned is an issue, that can be seen when the application is quite complex, and your page consists of multiple components. It can happen on some enterprise application, where you have huge datagrid and highcharts chart on one page, for example. What i meant by stuff is multiple asynchronous work and eventlisteners that exist inside the highcharts. And as we know it triggers changedetection

**Comment by KacperMadej** [comment]
@fclmman 

Thank you for all the information.
Is the `window.setTimeout` really needed? Looks like a not a perfect solution.

**Comment by fclmman** [comment]
@KacperMadej well, you were right, no need in timeout here, updated the pull request

**Comment by KacperMadej** [comment]
I had more time run more tests. The idea is interesting and solution for the problem works. It's possible to still use `_zone.run()` in chart's events if anyone wants to trigger change detection, so we are not taking away any features. The new way of running the wrapper should be optional to prevent breaking backward compatibility. Because of this the code will look differently, but will be based on your suggestions @fclmman , so thank you very much for all the help.

We'll need to prepare some documentation for the new feature.
I'll shortly open an issue for better tracking.

**Comment by fclmman** [comment]
Well, if you dont mind i can provide optional runotside, so that current behaviour will stay as default

**Comment by KacperMadej** [comment]
@fclmman 

If you could test new version 2.2.0 and check related commit (https://github.com/highcharts/highcharts-angular/commit/2ebcb07403718799e585ca132652204580a9eafd) to ensure that the suggested solution resolved the problem.

**Pull request closed without merging**
