### PR TITLE
Library build

### LINKED ISSUE #1: highcharts-chart.component.ts is not part of the compilation
> ERROR in ./node_modules/highcharts-angular/src/app/highcharts-chart.component.ts
Module build failed: Error: /Volumes/repo/test/ng4-highsoft/node_modules/highcharts-angular/src/app/highcharts-chart.component.ts is not part of the compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (/Volumes/repo/test/ng4-highsoft/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:619:23)
    at plugin.done.then (/Volumes/repo/test/ng4-highsoft/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
 @ ./node_modules/highcharts-angular/index.js 1:17-67
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

webpack: Failed to compile.

### LINKED ISSUE #15: Error: Unexpected value 'HighchartsChartComponent' declared by the module 'IstWerteModule'. Please add a @Pipe/@Directive/@Component annotation.
screen shot 2018-02-19 at 13 42 16

### LINKED ISSUE #24: Why not bundled into an Angular module ?
Hi,

I was wondering why this project is not bundled into a module. It feels very unnatural to me to add the highcharts component into the `declarations` array of my app module instead of declaring a module import in the corresponding `imports` array (as I do with every single angular dependency usually).

I'm not sure but I think the various build issues that some people encounter would be resolved by doing so.

I'm curious to know the reason behind this choice

Thanks in advance

### LINKED ISSUE #25: Not compatible with Angular 5.2.10
Just upgraded from Angular 5.2.9 to 5.2.10 and the compilation (AOT) is failing!
```
ERROR in Error during template compile of 'PlatformRef'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'Injectable'
    'Injectable' calls 'ɵmakeDecorator'.
node_modules/highcharts-angular/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
```

### LINKED ISSUE #29: Not compatible with Angular 6.0.0
We have just upgrade to angular6  and have this issue 
```

chunk {vendor} vendor.js, vendor.js.map (vendor) 325 kB [initial] [rendered]

ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/highcharts-angular/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

ℹ ｢wdm｣: Failed to compile.
```

```
Angular CLI: 6.0.1
Node: 9.11.1
OS: darwin x64
Angular: 6.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, upgrade

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.5.13
@angular-devkit/build-angular     0.5.13
@angular-devkit/build-optimizer   0.5.13
@angular-devkit/core              0.5.13
@angular-devkit/schematics        0.6.1 (cli-only)
@angular/cli                      <error>
@ngtools/webpack                  6.0.0-rc.11
@schematics/angular               0.6.1 (cli-only)
@schematics/update                0.6.1 (cli-only)
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0
```

### LINKED ISSUE #40: highcharts-angular should be disted with @angular as a peerDependency
Declaring `@angular/core`, etc. as `dependencies` can cause a duplicate copy of angular to be installed under `highcharts-angular`'s own `node_modules` folder, rather than reusing the already-installed one for a project. 

For example, these are the directories under my main `node_modules` folder:

```
/node_modules
    ...
    /highcharts-angular
        /node_modules
            /@angular   <-- duplicate, and it's Angular 5.2 rather than 6+ which is on my project
            /rxjs
            /symbol-observable
        /src
            /app
                highcharts-chart.component.ts
        .npmignore
        index.js
        LICENSE
        package.json
        README.md
```

This causes a separate copy of Angular to be used at runtime just for the `<highcharts-chart>` component, as well as runtime errors like:

```
StaticInjectorError(Platform: core)[HighchartsChartComponent -> ElementRef]: 
    NullInjectorError: No provider for ElementRef!
```

`@angular/core`, etc. should be declared as `peerDependencies` in package.json, and be given a very loose version number. Something like `>=2.0.0`, since it looks like this component will be compatible with anything Angular 2.0 and on.

`@angular/core`, etc. can also be declared under `devDependencies` for your local `highcharts-angular` development purposes.

### PR DESCRIPTION
**Pull request by gregjacobs**
Hey @KacperMadej. Here is a PR to build the proper Angular output library for the component using Angular CLI v6.

This PR should solve multiple issues: fixes #1, fixes #15, fixes #24, fixes #25, fixes #29, fixes #40

Couple quick things:

1. The `package.json` file that is npm published is now under the `./highcharts-angular` library subdirectory. I made the outer `package.json` as "private" to prevent accidental publishes of that package, and moved the keywords, repository, etc. information into the new library `package.json`.
1. I switched the version number to 2.0.0, since consumers will no longer need the `tsconfig.json` "include" workaround, and the package itself is consumed by importing `HighchartsChartModule` rather than declaring `HighchartsChartComponent` (as libraries should be consumed via an NgModule). Also updated the readme with this information.
1. Instead of publishing with `npm publish`, use the `npm run publish` script instead, which is a package.json script that publishes the `dist/highcharts-angular` directory. As such, no longer needed the `.npmignore` file
1. `.angular-cli.json` is now `angular.json` in CLI v6

### CODE REVIEW

**Comment by gregjacobs** [comment]
Just an fyi btw if you want to check out what the published package will look like: change 'publish' to 'pack' in `tasks/publish.js`, and then run `npm run publish` (which runs that .js script behind the scenes)

This will create a .tar.gz file under `dist/highcharts-angular/` that you can inspect

**Comment by KacperMadej** [comment]
@gregjacobs Thank you for the PR and all the work. All looks fine after checking except one thing, but this might be caused by something in my environment. When I tried to run `npm run publish` with changed `publish` to `pack` then a file is not created, unlike when running the `npm pack` in the `dist/highcharts-angular` folder. I can publish manually, so I just was wondering if the problem is familiar to you. I'll run some tests today and will merge the PR tomorrow (better to do this at the beginning of a day than by the end of it).

**Comment by gregjacobs** [comment]
Hey @KacperMadej. Np, had fun doing it!

Hmm, so I tested the script with pack and it gave me a .tar.gz file under the dist/highcharts-angular folder. Do you not see it in there? Def possible I messed something up last minute before submitting the PR. Also could have to do with me being on a Mac. Are you on Windows?

Unfortunately I’m at work right now and cant access GitHub (corporate blocks), but I can try to look at it tonight if it’s still not working

**Comment by KacperMadej** [comment]
@gregjacobs I'm on Windows. Manual `npm pack` runs fine, so it's good enough to confirm. I will check later how it runs on Mac. Thanks again!

**Comment by gregjacobs** [comment]
@KacperMadej Glad to hear it all worked well (minus the publish thing!) Sorry I didn't get a chance to take a look at that last night. I saw you merged and published 2.0.0 this morning though so I just installed it and it seems to be all good :)

**Pull request merged**
